# Generated by Django 5.0.3 on 2024-03-18 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestimo', models.DateField(verbose_name='Data de Empréstimo')),
                ('devolucao', models.DateField(verbose_name='Data de Devolução')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leitor', verbose_name='CPF do leitor')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.livro', verbose_name='Nome do Livro')),
            ],
        ),
    ]
